import type { FamilyMember, TreeArtifact } from './types';

export const initialFamilyMembers: FamilyMember[] = [
  {
    id: 'm1',
    name: '自分',
    role: '高校生',
    avatar: '👦',
    avatarColor: 'bg-emerald-100 border-emerald-300 text-emerald-800',
    wateredToday: false,
    streak: 14,
    isCurrentUser: true,
  },
  {
    id: 'm2',
    name: 'お父さん',
    role: '父',
    avatar: '👨‍💼',
    avatarColor: 'bg-blue-100 border-blue-300 text-blue-800',
    wateredToday: true,
    streak: 15,
  },
  {
    id: 'm3',
    name: 'お母さん',
    role: '母',
    avatar: '👩‍🍳',
    avatarColor: 'bg-amber-100 border-amber-300 text-amber-800',
    wateredToday: true,
    streak: 20,
  },
  {
    id: 'm4',
    name: '妹',
    role: '中学生',
    avatar: '👧',
    avatarColor: 'bg-rose-100 border-rose-300 text-rose-800',
    wateredToday: false,
    streak: 12,
  },
];

export const initialArtifacts: TreeArtifact[] = [
  {
    id: 'art-1',
    type: 'photo',
    author: 'お母さん',
    authorAvatar: '👩‍🍳',
    authorRole: '母',
    date: '今日 11:30',
    title: '今日のお弁当 🍱',
    content: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=600&q=80',
    coords: { x: 22, y: 38, rotate: -6 },
  },
  {
    id: 'art-2',
    type: 'photo',
    author: 'お父さん',
    authorAvatar: '👨‍💼',
    authorRole: '父',
    date: '昨日 18:20',
    title: '帰り道の夕焼け 🌇',
    content: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80',
    coords: { x: 70, y: 35, rotate: 5 },
  },
  {
    id: 'art-3',
    type: 'wood',
    author: '自分',
    authorAvatar: '👦',
    authorRole: '高校生',
    date: '2日前',
    title: '木製プレート',
    content: '期末テスト終わった！✨',
    coords: { x: 30, y: 64, rotate: -2 },
  },
  {
    id: 'art-4',
    type: 'wood',
    author: '妹',
    authorAvatar: '👧',
    authorRole: '中学生',
    date: '3日前',
    title: '木製プレート',
    content: '荷物送ったよ〜届いた？',
    coords: { x: 68, y: 60, rotate: 3 },
  },
];
